manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: magagne
      url-base: https://github.com/magagne
    - name: zzeneg
      url-base: https://github.com/zzeneg
    - name: bildermankawasaki
      url-base: https://github.com/bildermankawasaki

  projects:
    - name: zmk
      remote: magagne
      revision: edf5c0814fd3ea202e43aad2d68fd32e882a518c
      import: app/west.yml

    - name: zmk-raw-hid
      remote: zzeneg
      revision: main

    - name: zmk-keyboard-totem
      remote: bildermankawasaki
      revision: main

  self:
    path: config