description: Ploopy AutoMouseLayer configuration
compatible: "zmk,behavior-auto-mouse-layer"
properties:
  mac-base-layer:
    type: int
    required: true
  mac-mouse-layer:
    type: int
    required: true
  windows-base-layer:
    type: int
    required: true
  windows-mouse-layer:
    type: int
    required: true
